<?php

/*
Plugin Name: William's Talk
Description: Hello william! In order not to forget the roots.
Author: Andishe
Version: 1.0.0
*/

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
  die;
}

function william_settings_pages()
{
  add_menu_page(
    __( "William's talk", 'william' ),
    __( "William's talk", 'william' ),
    'manage_options',
    'william',
    'william_settings_page_markup',
    'dashicons-buddicons-activity',
    100
  );

  add_submenu_page(
    'william',
    __( 'Plugin Feature 2', 'wpplugin' ),
    __( 'collaboration', 'wpplugin' ),
    'manage_options',
    'wpplugin-feature-2',
    'wpplugin_settings_subpage_markup'
  );
}
add_action( 'admin_menu', 'william_settings_pages' );

// Add a link to your settings page in your plugin
function william_add_settings_link( $links ) {
    $settings_link = '<a href="admin.php?page=william">' . __( 'Settings', 'william' ) . '</a>';
    array_push( $links, $settings_link );
  	return $links;
}
$filter_name = "plugin_action_links_" . plugin_basename( __FILE__ );
add_filter( $filter_name, 'william_add_settings_link' );



function william_settings_page_markup()
{
  // Double check user capabilities
  if ( !current_user_can('manage_options') ) {
      return;
  }
  ?>
  <div class="wrap">
    <h1><?php esc_html_e( get_admin_page_title() ); ?></h1>
    <p><?php esc_html_e( 'Some content. yes it read this page markup from a function', 'william' ); ?></p>
    <p><?php esc_html_e( 'iv change this line all by myself', 'william' ); ?></p>
  </div>
  <?php
}

function william_settings_subpage_markup()
{
  // Double check user capabilities
  if ( !current_user_can('manage_options') ) {
      return;
  }
  ?>
  <div class="wrap">
    <h1><?php esc_html_e( get_admin_page_title() ); ?></h1>
    <p><?php esc_html_e( 'Some content.', 'william' ); ?></p>
  </div>
  <?php
}

function willi_lines() {
	$lines = "
	To be, or not to be: that is the question.
	To be, or not to be: that is the question.
	";

	$userq = "this is a qout generated by the user";
	$lines .= "\n".$userq;

	// Split every line
	$lines = explode( "\n", $lines );

	// Choose random line
	return wptexturize( $lines[ mt_rand( 0, count( $lines ) - 1 ) ] );
}

// Echo lines
function williams() {
	$chosen = willi_lines();
	$lang   = '';
	if ( 'en_' !== substr( get_user_locale(), 0, 3 ) ) {
		$lang = ' lang="en"';
	}

	printf(
		'<p id="williams"><span class="screen-reader-text">%s </span><span dir="ltr"%s>%s</span></p>',
		__( 'lines from williams: ' ),
		$lang,
		$chosen
	);
}

add_action( 'admin_notices', 'williams' );

function css() {
	echo "
	<style>
	@import url('https://fonts.googleapis.com/css2?family=Allison&display=swap');
	#williams {
		font-family: 'Amatic SC', cursive;
		font-weight: 300;
		float: right;
		font-size: 16px;
		color: #50575e;
		padding: 0px;
		margin: 2px 10px 5px 0px;
		animation-name: eminemanimation;
		animation-duration: 2s;
		}

		@keyframes eminemanimation {
		  0%   {font-size: 2px;}
		  100% {font-size: 16px;}
		}
	</style>
	";
}

add_action( 'admin_head', 'css' );
